### ISSUE TITLE
Apply this git config to automatically delete local branches that do not exist on remote

### ISSUE THREAD

**Issue by shreshthmohan** [plotthatstory/viz_co#15]
```git config --global fetch.prune true```

> If this configuration is set, running `git fetch` will also run `git remote prune` afterwards. `git remote prune` will delete inaccessible Git objects in your local repository that aren’t on remote. Deleting branches on remote but not locally will generate these inaccessible Git objects.
> 
> Having this option enabled minimizes the number of branches I have on my local machine. Any autocomplete feature that uses this list of branches is much easier to use with limited branches hanging around.

[Source](https://spin.atomicobject.com/2020/05/05/git-configurations-default/) (Using only the 2nd config among the three recommended.)

**Comment by plotthatstory** [comment]
Done. Closing.
